import os

os.system('clear')

welcome = """
Selamat datang di online string generator

Generator By : @absicth

Dapatkan API_ID and API_HASH dari my.telegram.org
"""
print(welcome)

lib = """
Pilih tipe string session:
p - Pyrogram 
t - Telethon  
q - Stop proses ini

"""
ask = input(lib)

if ask == "p":
    print("\nAnda Memilih Pyrogram")
    import pyrogram
    API_ID = input("Masukkan API_ID : ")
    API_HASH = input("Masukkan API_HASH : ")

    with pyrogram.Client(":memory:", api_id=API_ID,
                         api_hash=API_HASH) as client:
        session_str = client.export_session_string()
        info = client.get_me()
        fname = info.first_name
        msg = client.send_message("me", f"`{session_str}`")
        msg.reply_text("""
👆 TIni string pyrogram anda, generated by 
(C) Arul [@absicth]
""")
        print(
            f"\nBerhasil login sebagai {fname}  \n\nCek pesan tersimpan milik anda untuk mengambil Pyrogram String Session"
        )

elif ask == "t":
    print("\nAnda Memilih Telethon")
    from telethon.sync import TelegramClient
    from telethon.sessions import StringSession

    API_ID = input("Masukkan API_ID : ")
    API_HASH = input("Masukkan API_HASH : ")

    with TelegramClient(StringSession(), API_ID, API_HASH) as client:
        session_str = client.session.save()
        msg = client.send_message("me", f"`{session_str}`")
        msg.reply("""
👆 TIni string Telethon anda, generated by (C) Arul [@absicth]
""")
        print(
            "\nCek di pesan tersimpan milik anda untuk mengambil Telethon String Session"
        )

elif ask == "q":
    print("menghentikan semua proses")
    exit()

else:
    print("""
  Invalid Option Selected
  Please only Choose between p/t
  Stopping all Process
  Restart Repl
""")
